'''
======================
姓名：xx
QQ：xxxxxxxxxxx
手机号：131xxxx
公司地址：北京尚硅谷
======================
'''
name=input("请输入您的姓名：")
qqtel=int(input("请输入您的QQ："))
tel=int(input("请输入您的手机号："))
stil=input("请输入您的公司地址：")
print("==============================\n")
print("姓名：%s\n"%name)
print("QQ：%d\n"%qqtel)
print("手机号：%d\n"%tel)
print("公司地址：%s\n"%stil)
print("==============================")
